import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Avatar, Button, Card } from 'antd'

const inter = Inter({ subsets: ['latin'] })
import { Col, Divider, Row } from 'antd';
import Meta from 'antd/es/card/Meta'
import { EditOutlined, EllipsisOutlined, InfoCircleOutlined, MoreOutlined, SettingOutlined } from '@ant-design/icons'
import ProductCard from '../components/shared/ProductCard'
import HomeBanner from '../components/home/HomeBanner'
import FeaturedCategories from '../components/home/FeaturedCategories'
import { env } from '@/utils/envVariables'
import ProductItems from '@/components/shared/ProductItems'


export default function Home({ products }: { products: IProduct[] }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomeBanner />
			<ProductItems products={products} title='Featured Products' />
			<FeaturedCategories />
		</>
	)
}


// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {
	const res = await fetch(env.apiUrl + '/featured')
	const products: IProduct[] = await res.json()

	return {
		props: {
			products,
		},
	}
}