import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Avatar, Button, Card } from 'antd'

const inter = Inter({ subsets: ['latin'] })
import { Col, Divider, Row } from 'antd';
import Meta from 'antd/es/card/Meta'
import { EditOutlined, EllipsisOutlined, InfoCircleOutlined, MoreOutlined, SettingOutlined } from '@ant-design/icons'
import ProductCard from './components/ProductCard'
import HomeBanner from './components/home/HomeBanner'
import FeaturedItems from './components/home/FeaturedItems'
import FeaturedCategories from './components/home/FeaturedCategories'


export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomeBanner />
			<FeaturedItems />
			<FeaturedCategories />
		</>
	)
}
